apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubeshell-web.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
  {{- if eq .Values.target.kind "Deployment" }}
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
  {{- end }}
  {{- if eq .Values.target.kind "StatefulSet" }}
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get"]
  {{- end }}
  {{- if eq .Values.target.kind "DaemonSet" }}
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get"]
  {{- end }}
